# Product device tree and matching overlay
dtb-$(CONFIG_ARCH_SPRD) += iclass-c8pro.dtb
dtb-$(CONFIG_ARCH_SPRD) += iclass-c8pro-overlay.dtbo
iclass-c8pro-overlay.dtbo-base := iclass-c8pro.dtb
DTC_FLAGS_iclass-c8pro += -@
DTC_FLAGS_iclass-c8pro-overlay += -@
